[('192.168.122.121', 'administrator', 'Sungard01'), ('192.168.122.122', 'administrator', 'Sungard01')]
[('192.168.122.123', 'root', 'Sungard01'), ('192.168.122.124', 'root', 'Sungard01')]
20
connection created
connection created
connection created
connection created

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
TypeError: run() takes exactly 2 arguments (54 given)
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
TypeError: run() takes exactly 2 arguments (54 given)
Process Process-3:
Process Process-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "controller_test.py", line 71, in lin_connect
  File "controller_test.py", line 71, in lin_connect
    ssh.connect(hostname=lin[0], username=lin[1], password=lin[2])
    ssh.connect(hostname=lin[0], username=lin[1], password=lin[2])
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 305, in connect
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 305, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/site-packages/paramiko/util.py", line 269, in retry_on_signal
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/site-packages/paramiko/util.py", line 269, in retry_on_signal
    return function()
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 305, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return function()
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 305, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 110] Connection timed out
    return getattr(self._sock,name)(*args)
error: [Errno 110] Connection timed out

Closing remote connection
